---
title: "Red-backed salamander abundance and distribution in north-central Massachusetts"
author: "Joshua A. Harkness"
date: "2024-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages(gridExtra)
library(tidyverse)
library(broom)
library(stringr)
library(sf)
library(ggspatial)
library(readxl)
library(GGally)
library(gridExtra)
library(tidymodels)
```

## Load data
```{r}
df <- read_csv("/cloud/project/data/df.csv")
```

#### Hurdle model without interaction

```{r}
df1 <- na.omit(df)
hurdle_nb1 <- hurdle(n_ind ~ ft + ts + ba + st.ha + canopy.cover + cwd.con + vcwd.con + avg.dc + tot.snags + avg.snag.dbh + soil.ph, data = df1, dist = "negbin")
summary(hurdle_nb1)
```


```{r}
stepAIC(hurdle_nb1, direction = "both")
```
```{r}
hurdle_nb2 <- hurdle(n_ind ~ canopy.cover + avg.snag.dbh, data = df1, dist = "negbin")
summary(hurdle_nb2)
```
#### Hurdle model with forest type interaction
```{r}
hurdle_nb3 <- hurdle(n_ind ~ ft + ts + ba + st.ha + canopy.cover + cwd.con + vcwd.con + avg.dc + tot.snags + avg.snag.dbh + soil.ph + ft*ts + ts*ba + ts*soil.ph + ft*ba + ft*soil.ph, data = df1, dist = "negbin")
summary(hurdle_nb3)
```
```{r}
stepAIC(hurdle_nb3, direction = "both")
```


#### Hurdle model with multiple interaction
```{r}
hurdle_nb4 <- hurdle(n_ind ~ ft + ts + ba + st.ha + canopy.cover + cwd.con + vcwd.con + avg.dc + tot.snags + avg.snag.dbh + soil.ph + ft*ts + ts*ba + ts*soil.ph + ft*ba + ft*soil.ph + cwd.con * vcwd.con + st.ha * canopy.cover, data = df1, dist = "negbin")
summary(hurdle_nb4)
```
```{r}
stepAIC(hurdle_nb4, direction = "both")
```

```{r}
library(AICcmodavg)
models <- list(hurdle_nb1, hurdle_nb2, hurdle_nb3, hurdle_nb4)
mod.names <- c('Env model full', 'Env model reduced', 'Env model ft interaction', 'Env model mult interactions')
aictab(cand.set = models, modnames = mod.names)
```
Make table with `kable` of model comparisons.

### Predictive model
Create binomial `presence` variable for logistic regression.
```{r}
df <- df %>%
  mutate(presence = as.factor(case_when(n_ind >= 1 ~ 1, n_ind == 0 ~ n_ind)))
df
```

```{r}
set.seed(117)

abund_split <- initial_split(df, prop = 0.8)

train_data <- training(abund_split)
test_data <- testing(abund_split)
```

```{r}
glimpse(train_data)
glimpse(test_data)
```
Consider downsampling here.

```{r}
log_fit_presence <- logistic_reg(engine = "glm") %>%
  fit(presence ~ canopy.cover + avg.snag.dbh, data = train_data, family = "binomial")
```

```{r}
predict(log_fit_presence, test_data)
```

```{r}
presence_pred <- predict(log_fit_presence, test_data, type = "prob") %>%
  bind_cols(test_data %>% dplyr::select(presence, canopy.cover))
presence_pred
```

```{r}
presence_pred %>%
  arrange(desc(.pred_1)) %>%
  print(n = 10)
```


```{r}
presence_pred %>%
  roc_curve(
    truth = presence,
    .pred_1,
    event_level = "second"
  ) %>%
  autoplot()


```
Not a good fit.

