---
title: "Red-backed salamander abundance and distribution in north-central Massachusetts"
author: "Joshua A. Harkness"
date: "2024-02-02"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(stringr)
library(sf)
library(ggspatial)
library(readxl)
```

## 1. Introduction



## 2. Data
### Load Packages

### Load Datafiles from GitHub Repository
```{r}
plots <- read_csv("/cloud/project/data/hf131-01-plot.csv")
cwd <- read_csv("/cloud/project/data/hf131-03-cwd.csv")
aco <- read_csv("/cloud/project/data/hf131-04-aco.csv")
pc <- read_csv("/cloud/project/data/hf131-05-pc-abund.csv")
herps <- read_csv("/cloud/project/data/hf131-06-herps.csv")
```

```{r}
#Plots
glimpse(plots)
#ACO
glimpse(aco)
glimpse(pc)
glimpse(herps)
```

### Convert degrees, minutes, seconds to decimal degrees


```{r}
#latitude
plots <- plots %>%
  mutate(lat = str_replace_all(lat, "\xb0", ":"))

plots <- plots %>%
  mutate(lat = str_remove_all(lat, "N"))

plots <- plots %>%
  mutate(lat = str_remove_all(lat, "'"))

plots <- plots %>%
  mutate(lat = str_squish(lat))

#longitude
plots <- plots %>%
  mutate(long = str_replace_all(long, "\xb0", ":"))

plots <- plots %>%
  mutate(long = str_remove_all(long, "W"))

plots <- plots %>%
  mutate(long = str_remove_all(long, "'"))

plots <- plots %>%
  mutate(long = str_squish(long))
```

```{r}
#extract values to create separate columns for degrees, decimal minutes, and hemisphere


plots <- plots %>%
  mutate(lat_deg = str_extract_all(plots$lat, "..(?=:)"),
         lat_dm = str_extract_all(plots$lat, "(?<=:)......"),
         long_deg = str_extract_all(plots$long, "..(?=:)"),
         long_dm = str_extract_all(plots$long, "(?<=:)......"))

plots$lat_deg <- as.numeric(plots$lat_deg)
plots$lat_dm <- as.numeric(plots$lat_dm)
plots$long_deg <- as.numeric(plots$long_deg)
plots$long_dm <- as.numeric(plots$long_dm)
```
decimal degrees=d+m/60+s/3600

```{r}
lattest = 42 + 29.275 / 60
	
longtest = 71 + 53.891 / 60
```
seems to be a plausible location, right around HF in Petersham.

```{r}
coords <- plots %>%
  select(lat_deg, lat_dm, long_deg, long_dm) %>%
  mutate(lat_dd = lat_deg + lat_dm / 60,
         long_dd = long_deg + long_dm / 60)

coords$long_dd <- coords$long_dd*(-1)
```

```{r}
coords %>%
  ggplot(aes(x = long_dd, y = lat_dd)) +
  geom_point()
```
```{r}
mass_towns <- st_read("/cloud/project/data/Community Boundaries (Towns) from Survey Points.shp")
```

### Exploratory Visualizations

```{r}
plots_stations %>%
  ggplot(aes(x = site, y = soil.ph, fill = ft)) +
  geom_boxplot()
```

```{r}
plots_stations %>%
  ggplot(aes(x = site, y = ba, fill = ft)) +
  geom_boxplot()
```
```{r}
plots_stations %>%
  ggplot(aes(x = ft, y = soilt, fill = ft)) +
  geom_boxplot() +
  scale_color_viridis_c()
```

```{r}
plots %>%
  ggplot(aes(y = vcwd, x = ba)) +
  geom_col() +
  theme_bw() +
  labs(title = "Coarse Woody Debris and Basal Area",
       x = "Basal area (m2/ha)",
       y = "CWD volume (m3)")
```

### Plethodon cinereus morphometrics

```{r}
pc %>%
  ggplot(aes(x = tl, y = wt)) +
  geom_point() +
  geom_smooth()
```
```{r}
pc %>%
  drop_na(sex) %>%
  ggplot(aes(x = sex, y = wt)) +
  geom_boxplot()
```

### Other herp morphometrics
```{r}
herps %>%
  count(species, sort = TRUE)
```


```{r}
herps %>%
  ggplot(aes(x = species, y = tl, fill = species)) +
  geom_boxplot() +
  coord_flip()
```


## 3. Ethics review

## 4. Data analysis plan



